name: didi_mesaj
description: DÄ°DÄ° MESAJ Android uygulamasÄ±
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

